# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/matheogomez/Desktop/PDLS/ui/Backup.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BackupParent(object):
    def setupUi(self, BackupParent):
        BackupParent.setObjectName("BackupParent")
        BackupParent.resize(400, 51)
        self.Backup = QtWidgets.QWidget(BackupParent)
        self.Backup.setGeometry(QtCore.QRect(0, 0, 400, 50))
        self.Backup.setMinimumSize(QtCore.QSize(400, 50))
        self.Backup.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Inter 28pt")
        self.Backup.setFont(font)
        self.Backup.setAutoFillBackground(False)
        self.Backup.setStyleSheet("background-color: white; border-radius: 15;")
        self.Backup.setProperty("Timestamp", 0)
        self.Backup.setObjectName("Backup")
        self.BackupDesc = QtWidgets.QLabel(self.Backup)
        self.BackupDesc.setGeometry(QtCore.QRect(13, 28, 281, 20))
        font = QtGui.QFont()
        font.setFamily("Inter 28pt")
        self.BackupDesc.setFont(font)
        self.BackupDesc.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.BackupDesc.setStyleSheet("background-color: None; color:black")
        self.BackupDesc.setTextFormat(QtCore.Qt.RichText)
        self.BackupDesc.setObjectName("BackupDesc")
        self.BackupName = QtWidgets.QLabel(self.Backup)
        self.BackupName.setGeometry(QtCore.QRect(13, 0, 301, 30))
        font = QtGui.QFont()
        font.setFamily("Inter 28pt")
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.BackupName.setFont(font)
        self.BackupName.setStyleSheet("background-color: None; color:black")
        self.BackupName.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.BackupName.setObjectName("BackupName")
        self.BackupAccept = QtWidgets.QLabel(self.Backup)
        self.BackupAccept.setEnabled(True)
        self.BackupAccept.setGeometry(QtCore.QRect(320, 10, 71, 30))
        font = QtGui.QFont()
        font.setFamily("Inter 28pt")
        self.BackupAccept.setFont(font)
        self.BackupAccept.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BackupAccept.setFocusPolicy(QtCore.Qt.TabFocus)
        self.BackupAccept.setStyleSheet("background-color: #035fe7; color:white")
        self.BackupAccept.setScaledContents(True)
        self.BackupAccept.setAlignment(QtCore.Qt.AlignCenter)
        self.BackupAccept.setObjectName("BackupAccept")

        self.retranslateUi(BackupParent)
        QtCore.QMetaObject.connectSlotsByName(BackupParent)

    def retranslateUi(self, BackupParent):
        _translate = QtCore.QCoreApplication.translate
        BackupParent.setWindowTitle(_translate("BackupParent", "Form"))
        self.BackupDesc.setText(_translate("BackupParent", "19 plats • 12 descriptions"))
        self.BackupName.setText(_translate("BackupParent", "Version du 30/08/2024 à 11:30"))
        self.BackupAccept.setText(_translate("BackupParent", "Revenir"))
