# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/matheogomez/Desktop/PDLS/ui/CreateMenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(868, 810)
        MainWindow.setMaximumSize(QtCore.QSize(16777214, 16777215))
        font = QtGui.QFont()
        font.setUnderline(False)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setSizeIncrement(QtCore.QSize(0, 0))
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setStyleSheet("letter-spacing: 0.3px;")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setObjectName("gridLayout")
        self.MainFrame = QtWidgets.QFrame(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Inter 28pt")
        font.setUnderline(False)
        self.MainFrame.setFont(font)
        self.MainFrame.setAutoFillBackground(False)
        self.MainFrame.setStyleSheet("/* DO NOT EDIT /*")
        self.MainFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MainFrame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.MainFrame.setLineWidth(0)
        self.MainFrame.setObjectName("MainFrame")
        self.Title = QtWidgets.QLabel(self.MainFrame)
        self.Title.setGeometry(QtCore.QRect(69, 20, 712, 51))
        font = QtGui.QFont()
        font.setFamily("Inter 28pt")
        font.setPointSize(40)
        font.setBold(False)
        font.setWeight(50)
        self.Title.setFont(font)
        self.Title.setStyleSheet("color: white;")
        self.Title.setScaledContents(True)
        self.Title.setAlignment(QtCore.Qt.AlignCenter)
        self.Title.setWordWrap(False)
        self.Title.setObjectName("Title")
        self.DescEntry = QtWidgets.QPlainTextEdit(self.MainFrame)
        self.DescEntry.setGeometry(QtCore.QRect(69, 329, 712, 141))
        font = QtGui.QFont()
        font.setFamily("Inter 28pt")
        font.setPointSize(27)
        font.setKerning(True)
        self.DescEntry.setFont(font)
        self.DescEntry.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.DescEntry.setStyleSheet("QPlainTextEdit{color: black; background-color: rgb(255,255,255); border-radius: 20; padding-left:10; padding-right:10}")
        self.DescEntry.setTabChangesFocus(True)
        self.DescEntry.setDocumentTitle("")
        self.DescEntry.setUndoRedoEnabled(True)
        self.DescEntry.setLineWrapMode(QtWidgets.QPlainTextEdit.WidgetWidth)
        self.DescEntry.setPlainText("")
        self.DescEntry.setObjectName("DescEntry")
        self.TypeFrame = QtWidgets.QWidget(self.MainFrame)
        self.TypeFrame.setGeometry(QtCore.QRect(130, 195, 121, 102))
        self.TypeFrame.setMinimumSize(QtCore.QSize(0, 0))
        self.TypeFrame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Inter 28pt")
        self.TypeFrame.setFont(font)
        self.TypeFrame.setAutoFillBackground(False)
        self.TypeFrame.setStyleSheet("background-color: white; border-radius: 20")
        self.TypeFrame.setProperty("CompleteDesc", "")
        self.TypeFrame.setProperty("CroppedDesc", "")
        self.TypeFrame.setObjectName("TypeFrame")
        self.Starter = QtWidgets.QRadioButton(self.TypeFrame)
        self.Starter.setGeometry(QtCore.QRect(20, 5, 97, 30))
        font = QtGui.QFont()
        font.setFamily("Inter 28pt")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Starter.setFont(font)
        self.Starter.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Starter.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Starter.setStyleSheet("QRadioButton {\n"
"    color: black;\n"
"    background: none;\n"
"    spacing: 5px;\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border: 2px solid rgb(200,200,200);\n"
"    border-radius: 9px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color: rgb(167, 138, 242);\n"
"    border: 2px solid rgb(187,158,255);\n"
"}\n"
"\n"
"QRadioButton::indicator:focus {\n"
"    border: 2px solid rgb(104,203,255);\n"
"}")
        self.Starter.setCheckable(True)
        self.Starter.setChecked(False)
        self.Starter.setObjectName("Starter")
        self.Dessert = QtWidgets.QRadioButton(self.TypeFrame)
        self.Dessert.setGeometry(QtCore.QRect(20, 67, 97, 30))
        font = QtGui.QFont()
        font.setFamily("Inter 28pt")
        self.Dessert.setFont(font)
        self.Dessert.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Dessert.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Dessert.setStyleSheet("QRadioButton {\n"
"    color: black;\n"
"    background: none;\n"
"    spacing: 5px;\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border: 2px solid rgb(200,200,200);\n"
"    border-radius: 9px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color: rgb(167, 138, 242);\n"
"    border: 2px solid rgb(187,158,255);\n"
"}\n"
"\n"
"QRadioButton::indicator:focus {\n"
"    border: 2px solid rgb(104,203,255);\n"
"}")
        self.Dessert.setCheckable(True)
        self.Dessert.setObjectName("Dessert")
        self.DishButton = QtWidgets.QRadioButton(self.TypeFrame)
        self.DishButton.setGeometry(QtCore.QRect(20, 36, 97, 30))
        font = QtGui.QFont()
        font.setFamily("Inter 28pt")
        self.DishButton.setFont(font)
        self.DishButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.DishButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.DishButton.setStyleSheet("QRadioButton {\n"
"    color: black;\n"
"    background: none;\n"
"    spacing: 5px;\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border: 2px solid rgb(200,200,200);\n"
"    border-radius: 9px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color: rgb(167, 138, 242);\n"
"    border: 2px solid rgb(187,158,255);\n"
"}\n"
"\n"
"QRadioButton::indicator:focus {\n"
"    border: 2px solid rgb(104,203,255);\n"
"}")
        self.DishButton.setCheckable(True)
        self.DishButton.setChecked(False)
        self.DishButton.setObjectName("DishButton")
        self.SeasonFrame = QtWidgets.QWidget(self.MainFrame)
        self.SeasonFrame.setGeometry(QtCore.QRect(290, 215, 414, 61))
        self.SeasonFrame.setMinimumSize(QtCore.QSize(0, 0))
        self.SeasonFrame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Inter 28pt")
        self.SeasonFrame.setFont(font)
        self.SeasonFrame.setAutoFillBackground(False)
        self.SeasonFrame.setStyleSheet("background-color: white; border-radius: 20")
        self.SeasonFrame.setProperty("CompleteDesc", "")
        self.SeasonFrame.setProperty("CroppedDesc", "")
        self.SeasonFrame.setObjectName("SeasonFrame")
        self.Winter = QtWidgets.QLabel(self.SeasonFrame)
        self.Winter.setGeometry(QtCore.QRect(313, 10, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Inter 28pt")
        self.Winter.setFont(font)
        self.Winter.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Winter.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Winter.setStyleSheet("QLabel {background-color: rgb(220,220,220); color: black; border-radius: 15;} QLabel:focus {border: 2px solid rgb(104,203,255); }")
        self.Winter.setAlignment(QtCore.Qt.AlignCenter)
        self.Winter.setProperty("Activated", False)
        self.Winter.setObjectName("Winter")
        self.Summer = QtWidgets.QLabel(self.SeasonFrame)
        self.Summer.setGeometry(QtCore.QRect(111, 10, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Inter 28pt")
        self.Summer.setFont(font)
        self.Summer.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Summer.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Summer.setStyleSheet("QLabel {background-color: rgb(220,220,220); color: black; border-radius: 15;} QLabel:focus {border: 2px solid rgb(104,203,255); }")
        self.Summer.setAlignment(QtCore.Qt.AlignCenter)
        self.Summer.setProperty("Activated", False)
        self.Summer.setObjectName("Summer")
        self.Automn = QtWidgets.QLabel(self.SeasonFrame)
        self.Automn.setGeometry(QtCore.QRect(212, 10, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Inter 28pt")
        self.Automn.setFont(font)
        self.Automn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Automn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Automn.setStyleSheet("QLabel {background-color: rgb(220,220,220); color: black; border-radius: 15;} QLabel:focus {border: 2px solid rgb(104,203,255); }")
        self.Automn.setAlignment(QtCore.Qt.AlignCenter)
        self.Automn.setProperty("Activated", False)
        self.Automn.setObjectName("Automn")
        self.Spring = QtWidgets.QLabel(self.SeasonFrame)
        self.Spring.setGeometry(QtCore.QRect(10, 10, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Inter 28pt")
        self.Spring.setFont(font)
        self.Spring.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Spring.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Spring.setStyleSheet("QLabel {background-color: rgb(220,220,220); color: black; border-radius: 15} QLabel:focus {border: 2px solid rgb(104,203,255); }")
        self.Spring.setAlignment(QtCore.Qt.AlignCenter)
        self.Spring.setProperty("Activated", False)
        self.Spring.setObjectName("Spring")
        self.Save = QtWidgets.QLabel(self.MainFrame)
        self.Save.setEnabled(False)
        self.Save.setGeometry(QtCore.QRect(460, 502, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Inter 28pt")
        font.setPointSize(19)
        font.setBold(False)
        font.setWeight(50)
        self.Save.setFont(font)
        self.Save.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Save.setStyleSheet("QLabel{color: white; background-color: rgb(98, 184, 55); border-radius: 20; border: 2px solid rgb(88, 166, 52);} QLabel:focus {border: 2px solid rgb(104, 203, 255)} QLabel:disabled {background-color: rgb(141, 141, 141); border: 2px solid rgb(128, 128, 128)}")
        self.Save.setAlignment(QtCore.Qt.AlignCenter)
        self.Save.setObjectName("Save")
        self.Cancel = QtWidgets.QLabel(self.MainFrame)
        self.Cancel.setGeometry(QtCore.QRect(290, 502, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Inter 28pt")
        font.setPointSize(19)
        font.setBold(False)
        font.setWeight(50)
        self.Cancel.setFont(font)
        self.Cancel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Cancel.setStyleSheet("QLabel{color: white; background-color: #df2114; border-radius: 20; border: 2px solid #ae2118;} QLabel:focus {border: 2px solid rgb(104,203,255); }")
        self.Cancel.setAlignment(QtCore.Qt.AlignCenter)
        self.Cancel.setObjectName("Cancel")
        self.NameEntry = QtWidgets.QLineEdit(self.MainFrame)
        self.NameEntry.setGeometry(QtCore.QRect(69, 122, 712, 41))
        font = QtGui.QFont()
        font.setFamily("Inter 28pt")
        font.setPointSize(27)
        self.NameEntry.setFont(font)
        self.NameEntry.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.NameEntry.setStyleSheet("QLineEdit{color: black; background-color: rgb(255,255,255); border-radius: 20; padding-left:10; padding-right:10}")
        self.NameEntry.setObjectName("NameEntry")
        self.Success = QtWidgets.QLabel(self.MainFrame)
        self.Success.setGeometry(QtCore.QRect(69, 20, 712, 51))
        font = QtGui.QFont()
        font.setFamily("Inter 28pt")
        font.setPointSize(40)
        font.setBold(False)
        font.setWeight(50)
        self.Success.setFont(font)
        self.Success.setStyleSheet("color:white; background-color: rgb(98, 184, 55); border: 2px solid rgb(88, 166, 52); border-radius: 10px;")
        self.Success.setScaledContents(True)
        self.Success.setAlignment(QtCore.Qt.AlignCenter)
        self.Success.setWordWrap(False)
        self.Success.setObjectName("Success")
        self.gridLayout.addWidget(self.MainFrame, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setUnderline(False)
        self.statusbar.setFont(font)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 868, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setUnderline(False)
        self.menubar.setFont(font)
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.Starter, self.DishButton)
        MainWindow.setTabOrder(self.DishButton, self.Dessert)
        MainWindow.setTabOrder(self.Dessert, self.Spring)
        MainWindow.setTabOrder(self.Spring, self.Summer)
        MainWindow.setTabOrder(self.Summer, self.Automn)
        MainWindow.setTabOrder(self.Automn, self.Winter)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Title.setText(_translate("MainWindow", "Créer un plat"))
        self.DescEntry.setPlaceholderText(_translate("MainWindow", "Description"))
        self.Starter.setText(_translate("MainWindow", "Entrée"))
        self.Dessert.setText(_translate("MainWindow", "Dessert"))
        self.DishButton.setText(_translate("MainWindow", "Plat"))
        self.Winter.setText(_translate("MainWindow", "Hiver"))
        self.Summer.setText(_translate("MainWindow", "Été"))
        self.Automn.setText(_translate("MainWindow", "Automne"))
        self.Spring.setText(_translate("MainWindow", "Printemps"))
        self.Save.setText(_translate("MainWindow", "Sauvegarder"))
        self.Cancel.setText(_translate("MainWindow", "Quitter"))
        self.NameEntry.setPlaceholderText(_translate("MainWindow", "Nom"))
        self.Success.setText(_translate("MainWindow", "Plat créé avec succès !"))
import Images_rc
