# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/matheogomez/Desktop/PDLS/ui/ModifyMenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1368, 847)
        MainWindow.setMaximumSize(QtCore.QSize(16777214, 16777215))
        font = QtGui.QFont()
        font.setUnderline(False)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setUnderline(False)
        self.centralwidget.setFont(font)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setObjectName("gridLayout")
        self.MainFrame = QtWidgets.QFrame(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Inter 28pt")
        font.setUnderline(False)
        self.MainFrame.setFont(font)
        self.MainFrame.setAutoFillBackground(False)
        self.MainFrame.setStyleSheet("QWidget { background-color: transparent; } QScrollBar:vertical { border: none; background-color: transparent; width: 8px; margin: 15px 10px 0px 0px; } QScrollBar::handle:vertical { background-color: rgba(136, 136, 136, 1); min-height: 20px; border-radius: 4px; } ")
        self.MainFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MainFrame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.MainFrame.setLineWidth(0)
        self.MainFrame.setObjectName("MainFrame")
        self.ScrollArea2 = QtWidgets.QScrollArea(self.MainFrame)
        self.ScrollArea2.setGeometry(QtCore.QRect(93, 0, 426, 812))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ScrollArea2.sizePolicy().hasHeightForWidth())
        self.ScrollArea2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Inter 28pt")
        self.ScrollArea2.setFont(font)
        self.ScrollArea2.setAutoFillBackground(False)
        self.ScrollArea2.setStyleSheet("QWidget { background-color: transparent; } QScrollBar:vertical { border: none; background-color: transparent; width: 8px; margin: 15px 0px 15px 0px; } QScrollBar::handle:vertical { background-color: rgba(136, 136, 136, 1); min-height: 20px; border-radius: 4px; } ")
        self.ScrollArea2.setLineWidth(0)
        self.ScrollArea2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.ScrollArea2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.ScrollArea2.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.ScrollArea2.setWidgetResizable(True)
        self.ScrollArea2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.ScrollArea2.setObjectName("ScrollArea2")
        self.ScrollAreaWidgetContents = QtWidgets.QWidget()
        self.ScrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 422, 808))
        self.ScrollAreaWidgetContents.setStyleSheet("")
        self.ScrollAreaWidgetContents.setObjectName("ScrollAreaWidgetContents")
        self.ScrollArea2.setWidget(self.ScrollAreaWidgetContents)
        self.Save2 = QtWidgets.QLabel(self.MainFrame)
        self.Save2.setEnabled(False)
        self.Save2.setGeometry(QtCore.QRect(834, 547, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Inter 28pt")
        font.setPointSize(19)
        self.Save2.setFont(font)
        self.Save2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Save2.setStyleSheet("QLabel{color: white; background-color: rgb(98, 184, 55); border-radius: 20; border: 2px solid rgb(88, 166, 52)} QLabel:focus {border: 2px solid rgb(104, 203, 255)} QLabel:disabled {background-color: rgb(141, 141, 141); border: 2px solid rgb(128, 128, 128)}")
        self.Save2.setAlignment(QtCore.Qt.AlignCenter)
        self.Save2.setObjectName("Save2")
        self.DescEntry2 = QtWidgets.QPlainTextEdit(self.MainFrame)
        self.DescEntry2.setEnabled(False)
        self.DescEntry2.setGeometry(QtCore.QRect(549, 374, 712, 141))
        font = QtGui.QFont()
        font.setFamily("Inter 28pt")
        font.setPointSize(27)
        self.DescEntry2.setFont(font)
        self.DescEntry2.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.DescEntry2.setStyleSheet("QPlainTextEdit{color: black; background-color: rgb(255,255,255); border-radius: 20; padding-left:10; padding-right:10}")
        self.DescEntry2.setTabChangesFocus(True)
        self.DescEntry2.setDocumentTitle("")
        self.DescEntry2.setUndoRedoEnabled(True)
        self.DescEntry2.setLineWrapMode(QtWidgets.QPlainTextEdit.WidgetWidth)
        self.DescEntry2.setPlainText("")
        self.DescEntry2.setPlaceholderText("")
        self.DescEntry2.setObjectName("DescEntry2")
        self.Success2 = QtWidgets.QLabel(self.MainFrame)
        self.Success2.setGeometry(QtCore.QRect(549, 65, 712, 51))
        font = QtGui.QFont()
        font.setFamily("Inter 28pt")
        font.setPointSize(40)
        font.setBold(False)
        font.setWeight(50)
        self.Success2.setFont(font)
        self.Success2.setStyleSheet("color:white; background-color: rgb(98, 184, 55); border: 2px solid rgb(88, 166, 52); border-radius: 10px")
        self.Success2.setScaledContents(True)
        self.Success2.setAlignment(QtCore.Qt.AlignCenter)
        self.Success2.setWordWrap(False)
        self.Success2.setObjectName("Success2")
        self.Title2 = QtWidgets.QLabel(self.MainFrame)
        self.Title2.setGeometry(QtCore.QRect(549, 65, 712, 51))
        font = QtGui.QFont()
        font.setFamily("Inter 28pt")
        font.setPointSize(40)
        font.setBold(False)
        font.setWeight(50)
        self.Title2.setFont(font)
        self.Title2.setStyleSheet("color:white;")
        self.Title2.setScaledContents(True)
        self.Title2.setAlignment(QtCore.Qt.AlignCenter)
        self.Title2.setWordWrap(False)
        self.Title2.setObjectName("Title2")
        self.TypeFrame2 = QtWidgets.QWidget(self.MainFrame)
        self.TypeFrame2.setGeometry(QtCore.QRect(610, 240, 121, 102))
        self.TypeFrame2.setMinimumSize(QtCore.QSize(0, 0))
        self.TypeFrame2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Inter 28pt")
        self.TypeFrame2.setFont(font)
        self.TypeFrame2.setAutoFillBackground(False)
        self.TypeFrame2.setStyleSheet("background-color: white; border-radius: 20")
        self.TypeFrame2.setProperty("CompleteDesc", "")
        self.TypeFrame2.setProperty("CroppedDesc", "")
        self.TypeFrame2.setObjectName("TypeFrame2")
        self.Starter2 = QtWidgets.QRadioButton(self.TypeFrame2)
        self.Starter2.setEnabled(False)
        self.Starter2.setGeometry(QtCore.QRect(20, 5, 97, 30))
        font = QtGui.QFont()
        font.setFamily("Inter 28pt")
        self.Starter2.setFont(font)
        self.Starter2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Starter2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Starter2.setStyleSheet("QRadioButton {\n"
"    color: black;\n"
"    background: none;\n"
"    spacing: 5px;\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border: 2px solid rgb(200,200,200);\n"
"    border-radius: 9px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color: rgb(167, 138, 242);\n"
"    border: 2px solid rgb(187,158,255);\n"
"}\n"
"\n"
"QRadioButton::indicator:focus {\n"
"    border: 2px solid rgb(104,203,255);\n"
"}")
        self.Starter2.setCheckable(True)
        self.Starter2.setChecked(False)
        self.Starter2.setObjectName("Starter2")
        self.Dessert2 = QtWidgets.QRadioButton(self.TypeFrame2)
        self.Dessert2.setEnabled(False)
        self.Dessert2.setGeometry(QtCore.QRect(20, 67, 97, 30))
        font = QtGui.QFont()
        font.setFamily("Inter 28pt")
        self.Dessert2.setFont(font)
        self.Dessert2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Dessert2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Dessert2.setStyleSheet("QRadioButton {\n"
"    color: black;\n"
"    background: none;\n"
"    spacing: 5px;\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border: 2px solid rgb(200,200,200);\n"
"    border-radius: 9px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color: rgb(167, 138, 242);\n"
"    border: 2px solid rgb(187,158,255);\n"
"}\n"
"\n"
"QRadioButton::indicator:focus {\n"
"    border: 2px solid rgb(104,203,255);\n"
"}")
        self.Dessert2.setCheckable(True)
        self.Dessert2.setObjectName("Dessert2")
        self.DishButton2 = QtWidgets.QRadioButton(self.TypeFrame2)
        self.DishButton2.setEnabled(False)
        self.DishButton2.setGeometry(QtCore.QRect(20, 36, 97, 30))
        font = QtGui.QFont()
        font.setFamily("Inter 28pt")
        self.DishButton2.setFont(font)
        self.DishButton2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.DishButton2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.DishButton2.setStyleSheet("QRadioButton {\n"
"    color: black;\n"
"    background: none;\n"
"    spacing: 5px;\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border: 2px solid rgb(200,200,200);\n"
"    border-radius: 9px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color: rgb(167, 138, 242);\n"
"    border: 2px solid rgb(187,158,255);\n"
"}\n"
"\n"
"QRadioButton::indicator:focus {\n"
"    border: 2px solid rgb(104,203,255);\n"
"}")
        self.DishButton2.setCheckable(True)
        self.DishButton2.setChecked(False)
        self.DishButton2.setObjectName("DishButton2")
        self.SeasonFrame2 = QtWidgets.QWidget(self.MainFrame)
        self.SeasonFrame2.setGeometry(QtCore.QRect(770, 260, 414, 61))
        self.SeasonFrame2.setMinimumSize(QtCore.QSize(0, 0))
        self.SeasonFrame2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Inter 28pt")
        self.SeasonFrame2.setFont(font)
        self.SeasonFrame2.setAutoFillBackground(False)
        self.SeasonFrame2.setStyleSheet("background-color: white; border-radius: 20")
        self.SeasonFrame2.setProperty("CompleteDesc", "")
        self.SeasonFrame2.setProperty("CroppedDesc", "")
        self.SeasonFrame2.setObjectName("SeasonFrame2")
        self.Winter2 = QtWidgets.QLabel(self.SeasonFrame2)
        self.Winter2.setEnabled(False)
        self.Winter2.setGeometry(QtCore.QRect(313, 10, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Inter 28pt")
        self.Winter2.setFont(font)
        self.Winter2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Winter2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Winter2.setStyleSheet("QLabel {background-color: rgb(220,220,220); color: black; border-radius: 15;} QLabel:focus {border: 2px solid rgb(104,203,255); }")
        self.Winter2.setAlignment(QtCore.Qt.AlignCenter)
        self.Winter2.setProperty("Activated", False)
        self.Winter2.setObjectName("Winter2")
        self.Summer2 = QtWidgets.QLabel(self.SeasonFrame2)
        self.Summer2.setEnabled(False)
        self.Summer2.setGeometry(QtCore.QRect(111, 10, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Inter 28pt")
        self.Summer2.setFont(font)
        self.Summer2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Summer2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Summer2.setStyleSheet("QLabel {background-color: rgb(220,220,220); color: black; border-radius: 15;} QLabel:focus {border: 2px solid rgb(104,203,255); }")
        self.Summer2.setAlignment(QtCore.Qt.AlignCenter)
        self.Summer2.setProperty("Activated", False)
        self.Summer2.setObjectName("Summer2")
        self.Automn2 = QtWidgets.QLabel(self.SeasonFrame2)
        self.Automn2.setEnabled(False)
        self.Automn2.setGeometry(QtCore.QRect(212, 10, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Inter 28pt")
        self.Automn2.setFont(font)
        self.Automn2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Automn2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Automn2.setStyleSheet("QLabel {background-color: rgb(220,220,220); color: black; border-radius: 15;} QLabel:focus {border: 2px solid rgb(104,203,255); }")
        self.Automn2.setAlignment(QtCore.Qt.AlignCenter)
        self.Automn2.setProperty("Activated", False)
        self.Automn2.setObjectName("Automn2")
        self.Spring2 = QtWidgets.QLabel(self.SeasonFrame2)
        self.Spring2.setEnabled(False)
        self.Spring2.setGeometry(QtCore.QRect(10, 10, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Inter 28pt")
        self.Spring2.setFont(font)
        self.Spring2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Spring2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Spring2.setStyleSheet("QLabel {background-color: rgb(220,220,220); color: black; border-radius: 15;} QLabel:focus {border: 2px solid rgb(104,203,255); }")
        self.Spring2.setAlignment(QtCore.Qt.AlignCenter)
        self.Spring2.setProperty("Activated", False)
        self.Spring2.setObjectName("Spring2")
        self.Cancel2 = QtWidgets.QLabel(self.MainFrame)
        self.Cancel2.setGeometry(QtCore.QRect(663, 547, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Inter 28pt")
        font.setPointSize(19)
        self.Cancel2.setFont(font)
        self.Cancel2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Cancel2.setStyleSheet("QLabel{color: white; background-color: #df2114; border-radius: 20; border: 2px solid #ae2118} QLabel:focus {border: 2px solid rgb(104,203,255); }")
        self.Cancel2.setAlignment(QtCore.Qt.AlignCenter)
        self.Cancel2.setObjectName("Cancel2")
        self.NameEntry2 = QtWidgets.QLineEdit(self.MainFrame)
        self.NameEntry2.setEnabled(False)
        self.NameEntry2.setGeometry(QtCore.QRect(549, 167, 712, 41))
        font = QtGui.QFont()
        font.setFamily("Inter 28pt")
        font.setPointSize(27)
        self.NameEntry2.setFont(font)
        self.NameEntry2.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.NameEntry2.setStyleSheet("QLineEdit{color: black; background-color: rgb(255,255,255); border-radius: 20; padding-left:10; padding-right:10}")
        self.NameEntry2.setPlaceholderText("")
        self.NameEntry2.setObjectName("NameEntry2")
        self.Delete = QtWidgets.QLabel(self.MainFrame)
        self.Delete.setEnabled(False)
        self.Delete.setGeometry(QtCore.QRect(1005, 547, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Inter 28pt")
        font.setPointSize(19)
        self.Delete.setFont(font)
        self.Delete.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Delete.setStyleSheet("QLabel{color: white; background-color: rgb(223, 105, 20); border-radius: 20; border: 2px solid rgb(201, 87, 4)} QLabel:focus {border: 2px solid rgb(104, 203, 255)} QLabel:disabled {background-color: rgb(141,141,141); border: 2px solid rgb(128, 128, 128)};")
        self.Delete.setAlignment(QtCore.Qt.AlignCenter)
        self.Delete.setObjectName("Delete")
        self.gridLayout.addWidget(self.MainFrame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1368, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Save2.setText(_translate("MainWindow", "Sauvegarder"))
        self.Success2.setText(_translate("MainWindow", "Plat modifié avec succès !"))
        self.Title2.setText(_translate("MainWindow", "Modifier un plat"))
        self.Starter2.setText(_translate("MainWindow", "Entrée"))
        self.Dessert2.setText(_translate("MainWindow", "Dessert"))
        self.DishButton2.setText(_translate("MainWindow", "Plat"))
        self.Winter2.setText(_translate("MainWindow", "Hiver"))
        self.Summer2.setText(_translate("MainWindow", "Été"))
        self.Automn2.setText(_translate("MainWindow", "Automne"))
        self.Spring2.setText(_translate("MainWindow", "Printemps"))
        self.Cancel2.setText(_translate("MainWindow", "Quitter"))
        self.Delete.setText(_translate("MainWindow", "Supprimer"))
import Images_rc
